import { Team } from '../types/crew';

export const mockedTeams: Team[] = [
  {
    name: 'Unit 11',
    color: '#558B97',
    crew: [
      {
        id: '2204',
        name: 'A. Forgosh',
        initials: 'AF',
        color: '#3880A9',
        time: '0:0:0',
        signalStrength: 'high',
        temperature: 0,
        thesia_count: 0,
        relative_elevation: 2,
      },
      {
        id: 'Engineer - Seat 1',
        name: 'R. Tan 2206',
        initials: 'RT',
        color: '#3880A9',
        time: '0:0:0',
        signalStrength: 'high',
        temperature: 0,
        thesia_count: 0,
        relative_elevation: 2,
      },
      {
        id: 'ForcibleEntry - Seat 2',
        name: 'D. Lewis 2207',
        color: '#3880A9',
        initials: 'DL',
        time: '0:0:0',
        signalStrength: 'high',
        temperature: 0,
        thesia_count: 0,
        relative_elevation: 2,
      },
    ],
  },
  {
    name: 'Heavy Rescue',
    color: '#C69956',
    crew: [
      {
        id: 'RIT - Seat 2',
        name: 'S. Susanto 2205',
        initials: 'SS',
        color: '#9259A0',
        time: '0:0:0',
        signalStrength: 'high',
        temperature: 0,
        thesia_count: 0,
        relative_elevation: 3,
      },
      {
        id: 'RIT - Seat 3',
        name: 'A. Alan 2208',
        initials: 'AA',
        color: '#AE8C5A',
        time: '0:0:0',
        signalStrength: 'med',
        temperature: 0,
        thesia_count: 0,
        relative_elevation: 1,
      },
      // {
      //   id: 'Extrication - Seat 4',
      //   name: 'A. Brody 2210',
      //   initials: 'AB',
      //   color: '#AE8C5A',
      //   time: '0:0:0',
      //   signalStrength: 'med',
      //   temperature: 0,
      //   thesia_count: 0,
      //   relative_elevation: 1,
      // },
      {
        id: 'Lieutenant - Seat 1',
        name: 'A. Crenshaw 2209',
        initials: 'AC',
        color: '#AE8C5A',
        time: '0:0:0',
        signalStrength: 'high',
        temperature: 0,
        thesia_count: 0,
        relative_elevation: 1,
      },
    ],
  },
];
